# Generated by Django 5.2 on 2025-04-28 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='reset_password_tokens',
            new_name='reset_password_token',
        ),
    ]
