# Generated by Django 5.2 on 2025-04-28 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0003_alter_review_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='', max_length=400)),
                ('street', models.CharField(default='', max_length=500)),
                ('providence', models.CharField(default='', max_length=400)),
                ('country', models.CharField(default='', max_length=400)),
                ('phone_nu', models.CharField(default='', max_length=400)),
                ('total_amount', models.IntegerField(default=0)),
                ('PaymentMethod', models.CharField(choices=[('COD', 'Cod'), ('Card', 'Card')], default='COD', max_length=300)),
                ('paymentStatus', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=300)),
                ('orderStatus', models.CharField(choices=[('Processing', 'Proccesssing'), ('Shiped', 'Shiped'), ('Delivered', 'Delivered')], default='Processing', max_length=300)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderitems', to='order.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product')),
            ],
        ),
    ]
