# Generated by Django 5.2 on 2025-04-29 12:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='PaymentMethod',
        ),
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='orderStatus',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paymentStatus',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone_nu',
        ),
        migrations.RemoveField(
            model_name='order',
            name='providence',
        ),
        migrations.AddField(
            model_name='order',
            name='createAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(choices=[('COD', 'Cod'), ('CARD', 'Card')], default='COD', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_no',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='Processing', max_length=60),
        ),
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
    ]
